"""empty message

Revision ID: 0aeeb3bd9c54
Revises: dfc8f3462f82
Create Date: 2025-03-24 12:57:03.281705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aeeb3bd9c54'
down_revision = 'dfc8f3462f82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pricesheet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prereg_price', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('atd_price', sa.Integer(), nullable=True))
        batch_op.drop_column('base_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pricesheet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_price', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('atd_price')
        batch_op.drop_column('prereg_price')

    # ### end Alembic commands ###
