"""empty message

Revision ID: 11f4aef2b7a8
Revises: 7c600be86a13
Create Date: 2025-07-15 10:10:28.311245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11f4aef2b7a8'
down_revision = '7c600be86a13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_column('early_on')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('early_on', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
