"""empty message

Revision ID: 182ab0f80acb
Revises: 85edc8f65488
Create Date: 2025-03-25 08:24:15.281549

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '182ab0f80acb'
down_revision = '85edc8f65488'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_num', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('regs', sa.Integer(), nullable=True))
        batch_op.alter_column('payment_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.create_foreign_key(None, 'registrations', ['regs'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('payment_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_column('regs')
        batch_op.drop_column('check_num')

    # ### end Alembic commands ###
