"""empty message

Revision ID: 19a469f91cca
Revises: 3695b963b83b
Create Date: 2025-07-17 14:41:49.465457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19a469f91cca'
down_revision = '3695b963b83b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('earlyonrequest_riders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('earlyonrequest_id', sa.Integer(), nullable=True),
    sa.Column('registration_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['earlyonrequest_id'], ['earlyonrequest.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('earlyonrequest_registrations')
    with op.batch_alter_table('earlyonrider', schema=None) as batch_op:
        batch_op.drop_constraint('earlyonrider_earlyonrequest_id_fkey', type_='foreignkey')
        batch_op.drop_column('earlyonrequest_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('earlyonrider', schema=None) as batch_op:
        batch_op.add_column(sa.Column('earlyonrequest_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('earlyonrider_earlyonrequest_id_fkey', 'earlyonrequest', ['earlyonrequest_id'], ['id'], ondelete='CASCADE')

    op.create_table('earlyonrequest_registrations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('earlyonrequest_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('registration_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['earlyonrequest_id'], ['earlyonrequest.id'], name='earlyonrequest_registrations_earlyonrequest_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], name='earlyonrequest_registrations_registration_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='earlyonrequest_registrations_pkey')
    )
    op.drop_table('earlyonrequest_riders')
    # ### end Alembic commands ###
