"""empty message

Revision ID: 1e452b9908c6
Revises: f1473de2768e
Create Date: 2025-06-26 16:04:01.816897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e452b9908c6'
down_revision = 'f1473de2768e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('space_fee_amount', sa.Double(), nullable=True))
        batch_op.add_column(sa.Column('processing_fee_amount', sa.Integer(), nullable=True))
        batch_op.alter_column('amount',
               existing_type=sa.INTEGER(),
               type_=sa.Double(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Double(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('processing_fee_amount')
        batch_op.drop_column('space_fee_amount')

    # ### end Alembic commands ###
