"""empty message

Revision ID: 25bd7307b603
Revises: 19a469f91cca
Create Date: 2025-07-17 14:42:34.465489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25bd7307b603'
down_revision = '19a469f91cca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('earlyonrider', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adult', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('earlyonrider', schema=None) as batch_op:
        batch_op.drop_column('adult')

    # ### end Alembic commands ###
