"""empty message

Revision ID: 27658fad872a
Revises: 13c4fc8f93ad
Create Date: 2025-07-19 11:39:07.790758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27658fad872a'
down_revision = '13c4fc8f93ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventvariables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reservationist', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventvariables', schema=None) as batch_op:
        batch_op.drop_column('reservationist')

    # ### end Alembic commands ###
