"""empty message

Revision ID: 285d237671c7
Revises: 25bd7307b603
Create Date: 2025-07-17 14:46:24.857142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '285d237671c7'
down_revision = '25bd7307b603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('earlyonrequest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reg_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'registrations', ['reg_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('earlyonrequest', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('reg_id')

    # ### end Alembic commands ###
