"""empty message

Revision ID: 3695b963b83b
Revises: 13792b50d936
Create Date: 2025-07-17 14:15:03.382545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3695b963b83b'
down_revision = '13792b50d936'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('earlyonrequest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dept_approval_status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('autocrat_approval_status', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('earlyonrequest', schema=None) as batch_op:
        batch_op.drop_column('autocrat_approval_status')
        batch_op.drop_column('dept_approval_status')

    # ### end Alembic commands ###
