"""empty message

Revision ID: 4a43e78f067d
Revises: 285d237671c7
Create Date: 2025-07-17 14:49:11.904131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a43e78f067d'
down_revision = '285d237671c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('earlyonrequest_riders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('earlyonrider_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('earlyonrequest_riders_registration_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'earlyonrider', ['earlyonrider_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('registration_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('earlyonrequest_riders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('earlyonrequest_riders_registration_id_fkey', 'registrations', ['registration_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('earlyonrider_id')

    # ### end Alembic commands ###
