"""empty message

Revision ID: 5e45299ec9f3
Revises: cdc16597c1e5
Create Date: 2025-06-26 08:26:49.007631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e45299ec9f3'
down_revision = 'cdc16597c1e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merchant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merchant', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
