"""empty message

Revision ID: 6ab436535999
Revises: c66363197d7f
Create Date: 2025-06-25 18:47:03.873042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ab436535999'
down_revision = 'c66363197d7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merchant', schema=None) as batch_op:
        batch_op.drop_column('electricity_requset')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merchant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('electricity_requset', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
