"""empty message

Revision ID: 7b048a64f136
Revises: 91a771acf041
Create Date: 2025-07-15 11:52:30.536125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b048a64f136'
down_revision = '91a771acf041'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventvariables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merchant_bounced_check_fee', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventvariables', schema=None) as batch_op:
        batch_op.drop_column('merchant_bounced_check_fee')

    # ### end Alembic commands ###
