"""empty message

Revision ID: 85c985a45976
Revises: eb93688c555f
Create Date: 2025-07-17 11:35:31.010209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85c985a45976'
down_revision = 'eb93688c555f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('earlyonrider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(), nullable=False),
    sa.Column('lname', sa.String(), nullable=False),
    sa.Column('scaname', sa.String(), nullable=False),
    sa.Column('regid', sa.Integer(), nullable=True),
    sa.Column('earlyonrequest_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['earlyonrequest_id'], ['earlyonrequest.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['regid'], ['registrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('earlyonrider')
    # ### end Alembic commands ###
