"""empty message

Revision ID: 85edc8f65488
Revises: c40205760348
Create Date: 2025-03-24 15:21:20.214534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85edc8f65488'
down_revision = 'c40205760348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emergency_contact_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_phone', sa.String(), nullable=True))
        batch_op.drop_column('onsite_contact_group')
        batch_op.drop_column('onsite_contact_kingdom')
        batch_op.drop_column('offsite_contact_name')
        batch_op.drop_column('onsite_contact_name')
        batch_op.drop_column('offsite_contact_phone')
        batch_op.drop_column('onsite_contact_sca_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('onsite_contact_sca_name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('offsite_contact_phone', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('onsite_contact_name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('offsite_contact_name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('onsite_contact_kingdom', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('onsite_contact_group', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('emergency_contact_phone')
        batch_op.drop_column('emergency_contact_name')

    # ### end Alembic commands ###
