"""empty message

Revision ID: 87446df9b0a7
Revises: fab2684d185c
Create Date: 2025-06-27 18:35:53.839006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87446df9b0a7'
down_revision = 'fab2684d185c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('electricity_fee_amount', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('electricity_fee_amount')

    # ### end Alembic commands ###
