"""empty message

Revision ID: 88e329d04ba6
Revises: 4e7d402581a1
Create Date: 2025-03-24 14:11:12.274144

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '88e329d04ba6'
down_revision = '4e7d402581a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice',
    sa.Column('invoice_number', sa.Integer(), nullable=False),
    sa.Column('invoice_date', sa.DateTime(), nullable=False),
    sa.Column('invoice_payment_date', sa.DateTime(), nullable=True),
    sa.Column('invoice_status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('invoice_number')
    )
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.alter_column('fname',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('lname',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('paypal_donation',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('early_on',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('royal_departure_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.alter_column('reg_date_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_index('ix_registrations_reg_date_time')
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.drop_column('invoice_paid')
        batch_op.drop_column('refund_check_num')
        batch_op.drop_column('invoice_status')
        batch_op.drop_column('order_id')
        batch_op.drop_column('invoice_date')
        batch_op.drop_column('invoice_canceled')
        batch_op.drop_column('invoice_payment_date')
        batch_op.drop_column('invoice_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_number', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('invoice_payment_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('invoice_canceled', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('invoice_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('invoice_status', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('refund_check_num', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('invoice_paid', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('ix_registrations_reg_date_time', ['reg_date_time'], unique=False)
        batch_op.alter_column('reg_date_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('royal_departure_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('early_on',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
        batch_op.alter_column('paypal_donation',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
        batch_op.alter_column('lname',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('fname',
               existing_type=sa.VARCHAR(),
               nullable=False)

    op.drop_table('invoice')
    # ### end Alembic commands ###
