"""empty message

Revision ID: 8b6d8c47c864
Revises: 17b403727e00
Create Date: 2025-02-21 13:04:40.759166

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8b6d8c47c864'
down_revision = '17b403727e00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('minor_waiver', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('nmr_donation', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medallion', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('medallion')
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('nmr_donation')
        batch_op.drop_column('minor_waiver')

    # ### end Alembic commands ###
