"""empty message

Revision ID: 8ef587236b09
Revises: 7c53c529dbfe
Create Date: 2025-07-15 11:38:50.789503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ef587236b09'
down_revision = '7c53c529dbfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventvariables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merchant_processing_fee', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('merchant_late_processing_fee', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('merchant_squarefoot_fee', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventvariables', schema=None) as batch_op:
        batch_op.drop_column('merchant_squarefoot_fee')
        batch_op.drop_column('merchant_late_processing_fee')
        batch_op.drop_column('merchant_processing_fee')

    # ### end Alembic commands ###
