"""empty message

Revision ID: 8f9e5d4d1659
Revises: 27658fad872a
Create Date: 2025-07-20 12:39:23.041576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f9e5d4d1659'
down_revision = '27658fad872a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('early_on_approved', sa.Boolean(), nullable=True))
        batch_op.drop_column('early_on')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('early_on', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('early_on_approved')

    # ### end Alembic commands ###
