"""empty message

Revision ID: 9b883fae497b
Revises: e695ac990ca7
Create Date: 2025-06-27 12:28:56.726215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b883fae497b'
down_revision = 'e695ac990ca7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
	return

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
	return

    # ### end Alembic commands ###
