"""empty message

Revision ID: a8096aa608fb
Revises: f8ccdd273480
Create Date: 2025-07-18 08:28:18.855793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8096aa608fb'
down_revision = 'f8ccdd273480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('earlyonrequest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rider_cost', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rider_balance', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('invoice_number', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'invoice', ['invoice_number'], ['invoice_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('earlyonrequest', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('invoice_number')
        batch_op.drop_column('rider_balance')
        batch_op.drop_column('rider_cost')

    # ### end Alembic commands ###
