"""empty message

Revision ID: aebf24aaa5e3
Revises: 53736fcab798
Create Date: 2024-06-21 22:29:35.253380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aebf24aaa5e3'
down_revision = '53736fcab798'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chivalric_inspection_martial_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rapier_inspection_martial_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('registrations_chivalric_inspection_martial_fkey', type_='foreignkey')
        batch_op.drop_constraint('registrations_rapier_inspection_martial_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['rapier_inspection_martial_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['chivalric_inspection_martial_id'], ['id'])
        batch_op.drop_column('chivalric_inspection_martial')
        batch_op.drop_column('rapier_inspection_martial')

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rapier_inspection_martial', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('chivalric_inspection_martial', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('registrations_rapier_inspection_martial_fkey', 'users', ['rapier_inspection_martial'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('registrations_chivalric_inspection_martial_fkey', 'users', ['chivalric_inspection_martial'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('rapier_inspection_martial_id')
        batch_op.drop_column('chivalric_inspection_martial_id')

    # ### end Alembic commands ###

