"""empty message

Revision ID: bd84cf86e7ad
Revises: f14fa333bb25
Create Date: 2025-06-26 08:19:13.552572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd84cf86e7ad'
down_revision = 'f14fa333bb25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_column('mbr_num_exp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mbr_num_exp', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
