"""empty message

Revision ID: ce25e1a650a0
Revises: aebf24aaa5e3
Create Date: 2024-06-21 22:31:26.705577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce25e1a650a0'
down_revision = 'aebf24aaa5e3'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chivalric_inspection_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('rapier_inspection_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_column('rapier_inspection_date')
        batch_op.drop_column('chivalric_inspection_date')

    # ### end Alembic commands ###

