"""empty message

Revision ID: e1c97df97774
Revises: c4c7f3125f86
Create Date: 2025-03-24 13:41:30.032710

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e1c97df97774'
down_revision = 'c4c7f3125f86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reg_crossbows')
    op.drop_table('marshal_inspection')
    op.drop_table('reglogs')
    op.drop_table('reg_bows')
    op.drop_table('crossbows')
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_index('ix_registrations_reg_date_time')

    op.drop_table('incidentreport')
    op.drop_table('bows')
    op.drop_table('registrations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bows',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('bows_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('poundage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('bow_inspection_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('bow_inspection_marshal_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bow_inspection_marshal_id'], ['users.id'], name='bows_bow_inspection_marshal_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='bows_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('incidentreport',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('regid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('report_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('incident_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('reporting_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['regid'], ['registrations.id'], name='incidentreport_regid_fkey'),
    sa.ForeignKeyConstraint(['reporting_user_id'], ['users.id'], name='incidentreport_reporting_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='incidentreport_pkey')
    )
    op.create_table('registrations',
    sa.Column('regid', sa.INTEGER(), server_default=sa.text("nextval('registrations_regid_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fname', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('lname', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('scaname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('kingdom', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('event_ticket', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rate_mbr', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rate_age', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rate_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price_calc', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price_paid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price_due', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lodging', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pay_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('prereg_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mbr_num_exp', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mbr_num', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('requests', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('checkin', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('medallion', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('signature', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reg_date_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('state_province', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('zip', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('onsite_contact_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('onsite_contact_sca_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('onsite_contact_kingdom', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('onsite_contact_group', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('offsite_contact_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('offsite_contact_phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('prereg_date_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('invoice_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('invoice_paid', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('invoice_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('invoice_canceled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('refund_check_num', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('early_on', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('atd_paid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('atd_pay_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('invoice_payment_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('paypal_donation', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('invoice_email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('paypal_donation_amount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('invoice_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('royal_departure_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('royal_title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('minor_waiver', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nmr_donation', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('regid', name='registrations_pkey'),
    sa.UniqueConstraint('id', name='uq_id'),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.create_index('ix_registrations_reg_date_time', ['reg_date_time'], unique=False)

    op.create_table('crossbows',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('crossbows_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('inchpounds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('crossbow_inspection_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('crossbow_inspection_marshal_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['crossbow_inspection_marshal_id'], ['users.id'], name='crossbows_crossbow_inspection_marshal_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='crossbows_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('reg_bows',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('regid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bowid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bowid'], ['bows.id'], name='reg_bows_bowid_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['regid'], ['registrations.id'], name='reg_bows_regid_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='reg_bows_pkey')
    )
    op.create_table('reglogs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('regid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('userid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['regid'], ['registrations.id'], name='reglogs_regid_fkey'),
    sa.ForeignKeyConstraint(['userid'], ['users.id'], name='reglogs_userid_fkey'),
    sa.PrimaryKeyConstraint('id', name='reglogs_pkey')
    )
    op.create_table('marshal_inspection',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('regid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('inspection_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('inspection_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('inspecting_marshal_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('inspected', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['inspecting_marshal_id'], ['users.id'], name='marshal_inspection_inspecting_marshal_id_fkey'),
    sa.ForeignKeyConstraint(['regid'], ['registrations.id'], name='marshal_inspection_regid_fkey'),
    sa.PrimaryKeyConstraint('id', name='marshal_inspection_pkey')
    )
    op.create_table('reg_crossbows',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('regid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('crossbowid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['crossbowid'], ['crossbows.id'], name='reg_crossbows_crossbowid_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['regid'], ['registrations.id'], name='reg_crossbows_regid_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='reg_crossbows_pkey')
    )
    # ### end Alembic commands ###
