"""empty message

Revision ID: e57832149fc3
Revises: 5e45299ec9f3
Create Date: 2025-06-26 14:17:55.938368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e57832149fc3'
down_revision = '5e45299ec9f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merchant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_number', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'invoice', ['invoice_number'], ['invoice_number'])

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merchant_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'merchant', ['merchant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('merchant_id')

    with op.batch_alter_table('merchant', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('invoice_number')

    # ### end Alembic commands ###
