"""empty message

Revision ID: e695ac990ca7
Revises: 15ff3973050c
Create Date: 2025-06-27 09:21:55.531817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e695ac990ca7'
down_revision = '15ff3973050c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('incidentreport', schema=None) as batch_op:
        batch_op.drop_constraint('incidentreport_event_id_fkey', type_='foreignkey')
        batch_op.drop_column('event_id')

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_constraint('invoice_event_id_fkey', type_='foreignkey')
        batch_op.drop_column('event_id')

    with op.batch_alter_table('lodging', schema=None) as batch_op:
        batch_op.drop_constraint('lodging_event_id_fkey', type_='foreignkey')
        batch_op.drop_column('event_id')

    with op.batch_alter_table('merchant', schema=None) as batch_op:
        batch_op.drop_constraint('merchant_event_id_fkey', type_='foreignkey')
        batch_op.drop_column('event_id')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint('payment_event_id_fkey', type_='foreignkey')
        batch_op.drop_column('event_id')

    with op.batch_alter_table('pricesheet', schema=None) as batch_op:
        batch_op.drop_constraint('pricesheet_event_id_fkey', type_='foreignkey')
        batch_op.drop_column('event_id')

    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_constraint('registrations_event_id_fkey', type_='foreignkey')
        batch_op.drop_column('event_id')

    with op.batch_alter_table('reglogs', schema=None) as batch_op:
        batch_op.drop_constraint('reglogs_event_id_fkey', type_='foreignkey')
        batch_op.drop_column('event_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_event_id_fkey', type_='foreignkey')
        batch_op.drop_column('event_id')

    op.drop_table('event')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('users_event_id_fkey', 'event', ['event_id'], ['id'])

    with op.batch_alter_table('reglogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('reglogs_event_id_fkey', 'event', ['event_id'], ['id'])

    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('registrations_event_id_fkey', 'event', ['event_id'], ['id'])

    with op.batch_alter_table('pricesheet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('pricesheet_event_id_fkey', 'event', ['event_id'], ['id'])

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('payment_event_id_fkey', 'event', ['event_id'], ['id'])

    with op.batch_alter_table('merchant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('merchant_event_id_fkey', 'event', ['event_id'], ['id'])

    with op.batch_alter_table('lodging', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('lodging_event_id_fkey', 'event', ['event_id'], ['id'])

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('invoice_event_id_fkey', 'event', ['event_id'], ['id'])

    with op.batch_alter_table('incidentreport', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('incidentreport_event_id_fkey', 'event', ['event_id'], ['id'])

    op.create_table('event',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='event_pkey')
    )
    # ### end Alembic commands ###
