"""empty message

Revision ID: ea685f885816
Revises: 3a9130a6356c
Create Date: 2025-06-26 21:09:08.536674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea685f885816'
down_revision = '3a9130a6356c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_column('invoice_total')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_total', sa.DOUBLE_PRECISION(precision=53), sa.Computed('((registration_total + nmr_total) + donation_total)', persisted=True), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
