"""empty message

Revision ID: eb93688c555f
Revises: 2b9ea9d8a95e
Create Date: 2025-07-17 08:04:55.615638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb93688c555f'
down_revision = '2b9ea9d8a95e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('earlyonrequest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arrival_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('dept_approval_status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('autocrat_approval_status', sa.String(), nullable=True))
        batch_op.drop_column('approved')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('earlyonrequest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('autocrat_approval_status')
        batch_op.drop_column('dept_approval_status')
        batch_op.drop_column('arrival_date')

    # ### end Alembic commands ###
