"""empty message

Revision ID: f14fa333bb25
Revises: c23bd73050a1
Create Date: 2025-06-26 08:16:17.835428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f14fa333bb25'
down_revision = 'c23bd73050a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    return

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    return

    # ### end Alembic commands ###
