"""empty message

Revision ID: f8ccdd273480
Revises: 4a43e78f067d
Create Date: 2025-07-17 14:52:57.065883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8ccdd273480'
down_revision = '4a43e78f067d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('earlyonrider', schema=None) as batch_op:
        batch_op.add_column(sa.Column('minor', sa.Boolean(), nullable=True))
        batch_op.drop_column('adult')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('earlyonrider', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adult', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('minor')

    # ### end Alembic commands ###
