"""empty message

Revision ID: 0ab82a252d98
Revises: 726c5ebca5fc
Create Date: 2026-02-12 08:11:49.784601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ab82a252d98'
down_revision = '726c5ebca5fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crossbows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poundage', sa.Double(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crossbows', schema=None) as batch_op:
        batch_op.drop_column('poundage')

    # ### end Alembic commands ###
