"""empty message

Revision ID: 13792b50d936
Revises: 85c985a45976
Create Date: 2025-07-17 14:14:54.209545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13792b50d936'
down_revision = '85c985a45976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('earlyonrequest', schema=None) as batch_op:
        batch_op.drop_column('autocrat_approval_status')
        batch_op.drop_column('dept_approval_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('earlyonrequest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dept_approval_status', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('autocrat_approval_status', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
