"""empty message

Revision ID: 13c4fc8f93ad
Revises: 7f10014fb2d6
Create Date: 2025-07-19 11:30:20.831282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13c4fc8f93ad'
down_revision = '7f10014fb2d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventvariables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('autocrat1', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('autocrat2', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('autocrat3', sa.String(), nullable=True))

    with op.batch_alter_table('pricesheet', schema=None) as batch_op:
        batch_op.drop_column('nmr')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pricesheet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nmr', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('eventvariables', schema=None) as batch_op:
        batch_op.drop_column('autocrat3')
        batch_op.drop_column('autocrat2')
        batch_op.drop_column('autocrat1')

    # ### end Alembic commands ###
