"""registrations table

Revision ID: 1425963ef65e
Revises: 
Create Date: 2024-03-08 00:38:59.726279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1425963ef65e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registrations',
    sa.Column('regid', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('fname', sa.String(length=64), nullable=False),
    sa.Column('lname', sa.String(length=64), nullable=False),
    sa.Column('scaname', sa.String(length=64), nullable=False),
    sa.Column('event_ticket', sa.String(length=64), nullable=True),
    sa.Column('rate_mbr', sa.String(length=64), nullable=True),
    sa.Column('rate_age', sa.String(length=64), nullable=True),
    sa.Column('rate_date', sa.String(length=64), nullable=True),
    sa.Column('price_calc', sa.Integer(), nullable=True),
    sa.Column('price_paid', sa.Integer(), nullable=True),
    sa.Column('price_due', sa.Integer(), nullable=True),
    sa.Column('lodging', sa.String(length=64), nullable=True),
    sa.Column('pay_type', sa.String(length=64), nullable=True),
    sa.Column('prereg_status', sa.String(length=64), nullable=True),
    sa.Column('mbr_num_exp', sa.String(length=64), nullable=True),
    sa.Column('mbr_num', sa.Integer(), nullable=True),
    sa.Column('requests', sa.String(length=256), nullable=True),
    sa.Column('checkin', sa.DateTime(), nullable=True),
    sa.Column('reg_date_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('regid')
    )
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registrations_reg_date_time'), ['reg_date_time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registrations_reg_date_time'))

    op.drop_table('registrations')
    # ### end Alembic commands ###
