"""empty message

Revision ID: 15ff3973050c
Revises: 43ceb20db0b6
Create Date: 2025-06-26 21:22:35.895762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15ff3973050c'
down_revision = '43ceb20db0b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merchant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merchant', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###
