"""empty message

Revision ID: 174f97dc3ae8
Revises: 541e1b2a8fe6
Create Date: 2025-08-28 08:58:14.488733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '174f97dc3ae8'
down_revision = '541e1b2a8fe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_column('invoice_id')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('paypal_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paypal_id', sa.VARCHAR(), autoincrement=False, nullable=True))

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_id', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
