"""empty message

Revision ID: 17b403727e00
Revises: 9b9cb5371a8a
Create Date: 2024-11-01 13:12:15.309770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17b403727e00'
down_revision = '9b9cb5371a8a'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('royal_departure_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('royal_title', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_column('royal_title')
        batch_op.drop_column('royal_departure_date')

    # ### end Alembic commands ###

