"""empty message

Revision ID: 25d1a55751b2
Revises: 86ffea765896
Create Date: 2025-08-21 16:00:01.039699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25d1a55751b2'
down_revision = '86ffea765896'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_id', sa.String(), nullable=True))
        batch_op.drop_column('inovice_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inovice_id', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('invoice_id')

    # ### end Alembic commands ###
