"""empty message

Revision ID: 26f228b9ba73
Revises: 8d0598888a13
Create Date: 2025-06-27 12:31:13.271284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26f228b9ba73'
down_revision = '8d0598888a13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_total', sa.Numeric(precision=10, scale=2), sa.Computed('registration_total + nmr_total + donation_total + space_fee + processing_fee', ), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_column('invoice_total')

    # ### end Alembic commands ###
