"""empty message

Revision ID: 28777a4e851a
Revises: 5ddb933ed904
Create Date: 2024-03-08 22:36:24.494024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28777a4e851a'
down_revision = '5ddb933ed904'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_email')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.create_index('ix_user_email', ['email'], unique=True)

    # ### end Alembic commands ###

