"""empty message

Revision ID: 2b9ea9d8a95e
Revises: 367563c0913c
Create Date: 2025-07-17 07:53:31.393384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b9ea9d8a95e'
down_revision = '367563c0913c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('earlyonrequest_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('earlyonrequest_id', sa.Integer(), nullable=True),
    sa.Column('registration_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['earlyonrequest_id'], ['earlyonrequest.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registration_id'], ['registrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('earlyonrequest', schema=None) as batch_op:
        batch_op.drop_constraint('earlyonrequest_regid_fkey', type_='foreignkey')
        batch_op.drop_column('regid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('earlyonrequest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('regid', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('earlyonrequest_regid_fkey', 'registrations', ['regid'], ['id'], ondelete='CASCADE')

    op.drop_table('earlyonrequest_registrations')
    # ### end Alembic commands ###
