"""empty message

Revision ID: 3a9130a6356c
Revises: 1e452b9908c6
Create Date: 2025-06-26 16:16:22.574023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a9130a6356c'
down_revision = '1e452b9908c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merchant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('space_fee_balance', sa.Double(), nullable=False))
        batch_op.add_column(sa.Column('processing_fee_balance', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('electricity_fee', sa.Double(), nullable=False))
        batch_op.add_column(sa.Column('electricity_balance', sa.Double(), nullable=False))
        batch_op.alter_column('estimated_date_of_arrival',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merchant', schema=None) as batch_op:
        batch_op.alter_column('estimated_date_of_arrival',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.drop_column('electricity_balance')
        batch_op.drop_column('electricity_fee')
        batch_op.drop_column('processing_fee_balance')
        batch_op.drop_column('space_fee_balance')

    # ### end Alembic commands ###
