"""empty message

Revision ID: 4067d8f6c2ad
Revises: 7b048a64f136
Create Date: 2025-07-16 15:33:25.150837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4067d8f6c2ad'
down_revision = '7b048a64f136'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('eventvariables', schema=None) as batch_op:
        batch_op.alter_column('merchant_bounced_check_fee',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'departments', ['department_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('department_id')

    with op.batch_alter_table('eventvariables', schema=None) as batch_op:
        batch_op.alter_column('merchant_bounced_check_fee',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.drop_table('departments')
    # ### end Alembic commands ###
