"""empty message

Revision ID: 41dda83512ae
Revises: b8432dadb790
Create Date: 2025-08-28 09:52:08.681968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41dda83512ae'
down_revision = 'b8432dadb790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_recruitmentschedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('recruitmentschedule_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recruitmentschedule_id'], ['recruitmentschedule.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_recruitmentschedule')
    # ### end Alembic commands ###
