"""Registrations table

Revision ID: 43ce598449b5
Revises: 1425963ef65e
Create Date: 2024-03-08 01:01:47.282147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43ce598449b5'
down_revision = '1425963ef65e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mbr_exp', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_column('mbr_exp')

    # ### end Alembic commands ###
