"""empty message

Revision ID: 43ceb20db0b6
Revises: ea685f885816
Create Date: 2025-06-26 21:09:20.452603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43ceb20db0b6'
down_revision = 'ea685f885816'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_total', sa.Double(), sa.Computed('registration_total + nmr_total + donation_total + space_fee + processing_fee', ), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_column('invoice_total')

    # ### end Alembic commands ###
