"""empty message

Revision ID: 4751d9c93cdd
Revises: 0aeeb3bd9c54
Create Date: 2025-03-24 13:16:19.674015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4751d9c93cdd'
down_revision = '0aeeb3bd9c54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
