"""empty message

Revision ID: 486838dc5cea
Revises: 8853793beefc
Create Date: 2025-12-04 13:42:57.695536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '486838dc5cea'
down_revision = '8853793beefc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recruitmentschedule', schema=None) as batch_op:
        batch_op.drop_constraint('recruitmentschedule_volunteer_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'volunteer', ['volunteer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recruitmentschedule', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('recruitmentschedule_volunteer_id_fkey', 'users', ['volunteer_id'], ['id'])

    # ### end Alembic commands ###
