"""empty message

Revision ID: 4c55ab66c9e2
Revises: 60c23086df2e
Create Date: 2025-03-27 15:53:52.191668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c55ab66c9e2'
down_revision = '60c23086df2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_column('balance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
