"""empty message

Revision ID: 53736fcab798
Revises: bf1926832294
Create Date: 2024-06-21 21:51:45.256305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53736fcab798'
down_revision = 'bf1926832294'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chivalric_inspection_martial', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rapier_inspection_martial', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('chivalric_inspection', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('rapier_inspection', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['rapier_inspection_martial'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['chivalric_inspection_martial'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('rapier_inspection')
        batch_op.drop_column('chivalric_inspection')
        batch_op.drop_column('rapier_inspection_martial')
        batch_op.drop_column('chivalric_inspection_martial')

    # ### end Alembic commands ###

