"""empty message

Revision ID: 59e55d070b87
Revises: 8b6d8c47c864
Create Date: 2025-02-21 22:08:32.244548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59e55d070b87'
down_revision = '8b6d8c47c864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poundage', sa.Double(), nullable=True),
    sa.Column('bow_inspection_martial_id', sa.Integer(), nullable=True),
    sa.Column('bow_inspection_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bow_inspection_martial_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crossbows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inchpounds', sa.Double(), nullable=True),
    sa.Column('crossbow_inspection_martial_id', sa.Integer(), nullable=True),
    sa.Column('crossbow_inspection_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['crossbow_inspection_martial_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('martial_inspection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regid', sa.Integer(), nullable=True),
    sa.Column('inspection_type', sa.String(), nullable=True),
    sa.Column('inspection_date', sa.DateTime(), nullable=True),
    sa.Column('inspecting_martial_id', sa.Integer(), nullable=True),
    sa.Column('inspected', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['inspecting_martial_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['regid'], ['registrations.regid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reg_bows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regid', sa.Integer(), nullable=True),
    sa.Column('bowid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bowid'], ['bows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['regid'], ['registrations.regid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reg_crossbows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regid', sa.Integer(), nullable=True),
    sa.Column('crossbowid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['crossbowid'], ['crossbows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['regid'], ['registrations.regid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reg_crossbows')
    op.drop_table('reg_bows')
    op.drop_table('martial_inspection')
    op.drop_table('crossbows')
    op.drop_table('bows')
    # ### end Alembic commands ###
