"""empty message

Revision ID: 5a79970d3c47
Revises: a8096aa608fb
Create Date: 2025-07-18 09:15:04.772963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a79970d3c47'
down_revision = 'a8096aa608fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rider_fee', sa.Integer(), nullable=True))

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rider_fee_amount', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('rider_fee_amount')

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_column('rider_fee')

    # ### end Alembic commands ###
