"""empty message

Revision ID: 6a19edaae4e4
Revises: ccf2c8d4d4b5
Create Date: 2025-06-25 16:00:01.879552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a19edaae4e4'
down_revision = 'ccf2c8d4d4b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(), nullable=False),
    sa.Column('sca_name', sa.String(), nullable=False),
    sa.Column('fname', sa.String(), nullable=False),
    sa.Column('lname', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('text_permission', sa.Boolean(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state_province', sa.String(), nullable=True),
    sa.Column('zip', sa.Integer(), nullable=True),
    sa.Column('frontage_width', sa.Integer(), nullable=False),
    sa.Column('frontage_depth', sa.Integer(), nullable=False),
    sa.Column('space_fee', sa.Integer(), nullable=False),
    sa.Column('additional_space_information', sa.Text(), nullable=True),
    sa.Column('processing_fee', sa.Integer(), nullable=False),
    sa.Column('merchant_fee', sa.Integer(), nullable=False),
    sa.Column('electricity_requset', sa.Text(), nullable=True),
    sa.Column('food_merchant_agreement', sa.Boolean(), nullable=True),
    sa.Column('estimated_date_of_arrival', sa.Date(), nullable=True),
    sa.Column('service_animal', sa.Boolean(), nullable=True),
    sa.Column('last_3_years', sa.Boolean(), nullable=True),
    sa.Column('vehicle_length', sa.Integer(), nullable=True),
    sa.Column('vehicle_license_plate', sa.String(), nullable=True),
    sa.Column('vehicle_state', sa.String(), nullable=True),
    sa.Column('trailer_length', sa.Integer(), nullable=True),
    sa.Column('trailer_license_plate', sa.String(), nullable=True),
    sa.Column('trailer_state', sa.String(), nullable=True),
    sa.Column('signature', sa.String(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('merchant')
    # ### end Alembic commands ###
