"""empty message

Revision ID: 6e2e2543b947
Revises: ce25e1a650a0
Create Date: 2024-06-24 09:28:38.799704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e2e2543b947'
down_revision = 'ce25e1a650a0'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poundage', sa.Double(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crossbows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inchpounds', sa.Double(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reg_bows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regid', sa.Integer(), nullable=True),
    sa.Column('bowid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bowid'], ['bows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['regid'], ['registrations.regid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reg_crossbows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regid', sa.Integer(), nullable=True),
    sa.Column('crossbowid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['crossbowid'], ['crossbows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['regid'], ['registrations.regid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reg_crossbows')
    op.drop_table('reg_bows')
    op.drop_table('crossbows')
    op.drop_table('bows')
    # ### end Alembic commands ###

