"""empty message

Revision ID: 70f3a08ccf09
Revises: 5a79970d3c47
Create Date: 2025-07-18 09:28:50.721998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70f3a08ccf09'
down_revision = '5a79970d3c47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('earlyonrequest_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'earlyonrequest', ['earlyonrequest_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('earlyonrequest_id')

    # ### end Alembic commands ###
