"""registrations table

Revision ID: 722858defa36
Revises: 09b873e4bb8d
Create Date: 2024-03-08 01:16:17.277364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '722858defa36'
down_revision = '09b873e4bb8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kingdom', sa.String(length=64), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_column('kingdom')

    # ### end Alembic commands ###
