"""empty message

Revision ID: 726c5ebca5fc
Revises: 88c27f17c5e3
Create Date: 2026-02-10 12:00:34.614464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '726c5ebca5fc'
down_revision = '88c27f17c5e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('combat_archery_type', sa.String(), nullable=True))

    with op.batch_alter_table('crossbows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('combat_archery_type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crossbows', schema=None) as batch_op:
        batch_op.drop_column('combat_archery_type')

    with op.batch_alter_table('bows', schema=None) as batch_op:
        batch_op.drop_column('combat_archery_type')

    # ### end Alembic commands ###
