"""empty message

Revision ID: 752addc103cf
Revises: 4e94151fa57a
Create Date: 2025-09-04 13:45:16.011699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '752addc103cf'
down_revision = '4e94151fa57a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registration_invoices')
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_number', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'invoice', ['invoice_number'], ['invoice_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('invoice_number')

    op.create_table('registration_invoices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('reg_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('invoice_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.invoice_number'], name='registration_invoices_invoice_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reg_id'], ['registrations.id'], name='registration_invoices_reg_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='registration_invoices_pkey')
    )
    # ### end Alembic commands ###
