"""registrations table

Revision ID: 752d7e7f9d18
Revises: 722858defa36
Create Date: 2024-03-08 01:21:54.309934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '752d7e7f9d18'
down_revision = '722858defa36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kingdom', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('medallion', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_column('medallion')
        batch_op.drop_column('kingdom')

    # ### end Alembic commands ###
