"""empty message

Revision ID: 7c009a6f9362
Revises: a572a9403f31
Create Date: 2024-10-17 08:39:33.155527

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7c009a6f9362'
down_revision = 'a572a9403f31'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_constraint('registrations_rapier_inspection_martial_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('registrations_chivalric_inspection_martial_id_fkey', type_='foreignkey')
        batch_op.drop_column('chivalric_inspection_date')
        batch_op.drop_column('rapier_inspection_martial_id')
        batch_op.drop_column('rapier_inspection_date')
        batch_op.drop_column('chivalric_inspection_martial_id')
        batch_op.drop_column('chivalric_inspection')
        batch_op.drop_column('rapier_inspection')

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rapier_inspection', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('chivalric_inspection', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('chivalric_inspection_martial_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rapier_inspection_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rapier_inspection_martial_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('chivalric_inspection_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('registrations_chivalric_inspection_martial_id_fkey', 'users', ['chivalric_inspection_martial_id'], ['id'])
        batch_op.create_foreign_key('registrations_rapier_inspection_martial_id_fkey', 'users', ['rapier_inspection_martial_id'], ['id'])

    op.create_table('bows',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('bows_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('poundage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('bow_inspection_martial_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bow_inspection_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bow_inspection_martial_id'], ['users.id'], name='bows_bow_inspection_martial_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='bows_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('reg_crossbows',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('regid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('crossbowid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['crossbowid'], ['crossbows.id'], name='reg_crossbows_crossbowid_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['regid'], ['registrations.regid'], name='reg_crossbows_regid_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='reg_crossbows_pkey')
    )
    op.create_table('crossbows',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('inchpounds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('crossbow_inspection_martial_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('crossbow_inspection_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['crossbow_inspection_martial_id'], ['users.id'], name='crossbows_crossbow_inspection_martial_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='crossbows_pkey')
    )
    op.create_table('reg_bows',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('regid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bowid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bowid'], ['bows.id'], name='reg_bows_bowid_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['regid'], ['registrations.regid'], name='reg_bows_regid_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='reg_bows_pkey')
    )
    # ### end Alembic commands ###

