"""empty message

Revision ID: 7c600be86a13
Revises: 87446df9b0a7
Create Date: 2025-07-15 09:59:18.223574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c600be86a13'
down_revision = '87446df9b0a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventvariables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('event_title', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('merchant_application_deadline', sa.Date(), nullable=False),
    sa.Column('merchantcrat_email', sa.String(), nullable=False),
    sa.Column('marchantcrat_phone', sa.String(), nullable=False),
    sa.Column('preregistration_open_date', sa.Date(), nullable=True),
    sa.Column('preregistration_close_date', sa.Date(), nullable=False),
    sa.Column('merchant_preregistration_open_date', sa.Date(), nullable=False),
    sa.Column('merchant_preregistration_close_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('merchant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ropes_front', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('ropes_back', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('ropes_left', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('ropes_right', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('merchant', schema=None) as batch_op:
        batch_op.drop_column('ropes_right')
        batch_op.drop_column('ropes_left')
        batch_op.drop_column('ropes_back')
        batch_op.drop_column('ropes_front')

    op.drop_table('eventvariables')
    # ### end Alembic commands ###
