"""empty message

Revision ID: 8853793beefc
Revises: eeaad67fd7ae
Create Date: 2025-12-04 13:42:20.455252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8853793beefc'
down_revision = 'eeaad67fd7ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volunteer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(), nullable=False),
    sa.Column('lname', sa.String(), nullable=False),
    sa.Column('scaname', sa.String(), nullable=True),
    sa.Column('kingdom_id', sa.Integer(), nullable=True),
    sa.Column('lodging_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kingdom_id'], ['kingdom.id'], ),
    sa.ForeignKeyConstraint(['lodging_id'], ['lodging.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('volunteer')
    # ### end Alembic commands ###
