"""empty message

Revision ID: 8b55ae9358a7
Revises: f39d9a30dd60
Create Date: 2025-02-17 08:22:29.617198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b55ae9358a7'
down_revision = 'f39d9a30dd60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('martial_inspection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inspection_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('inspection_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('inspecting_martial_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('inspected', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['inspecting_martial_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('martial_inspection', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('inspected')
        batch_op.drop_column('inspecting_martial_id')
        batch_op.drop_column('inspection_date')
        batch_op.drop_column('inspection_type')

    # ### end Alembic commands ###
