"""empty message

Revision ID: 91a771acf041
Revises: 8ef587236b09
Create Date: 2025-07-15 11:40:34.341480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91a771acf041'
down_revision = '8ef587236b09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventvariables', schema=None) as batch_op:
        batch_op.alter_column('merchant_processing_fee',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('merchant_late_processing_fee',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('merchant_squarefoot_fee',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventvariables', schema=None) as batch_op:
        batch_op.alter_column('merchant_squarefoot_fee',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('merchant_late_processing_fee',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('merchant_processing_fee',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
