"""empty message

Revision ID: 9bcb050e7d06
Revises: 3be3d7842f6e
Create Date: 2025-07-30 10:02:58.020493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bcb050e7d06'
down_revision = '3be3d7842f6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reg_id', sa.Integer(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.invoice_number'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reg_id'], ['registrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eventvariables', schema=None) as batch_op:
        batch_op.alter_column('preregistration_open_date',
               existing_type=sa.DATE(),
               nullable=False)

    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.drop_constraint('registrations_invoice_number_fkey', type_='foreignkey')
        batch_op.drop_column('invoice_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_number', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('registrations_invoice_number_fkey', 'invoice', ['invoice_number'], ['invoice_number'])
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('eventvariables', schema=None) as batch_op:
        batch_op.alter_column('preregistration_open_date',
               existing_type=sa.DATE(),
               nullable=True)

    op.drop_table('registration_invoices')
    # ### end Alembic commands ###
