"""empty message

Revision ID: 9e8691201827
Revises: df4f2462d433
Create Date: 2025-02-17 10:32:50.725586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e8691201827'
down_revision = 'df4f2462d433'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidentreport', schema=None) as batch_op:
        batch_op.add_column(sa.Column('incident_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidentreport', schema=None) as batch_op:
        batch_op.drop_column('incident_date')

    # ### end Alembic commands ###
