"""empty message

Revision ID: a32f2e7d606a
Revises: fd4eb0146799
Create Date: 2025-08-02 15:36:18.041916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a32f2e7d606a'
down_revision = 'fd4eb0146799'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduledevent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_instructor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_instructor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduledevent', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_instructor_id')

    # ### end Alembic commands ###
