"""empty message

Revision ID: acc2c2b889b1
Revises: e57832149fc3
Create Date: 2025-06-26 15:01:22.266480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acc2c2b889b1'
down_revision = 'e57832149fc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('space_fee', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('processing_fee', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_column('processing_fee')
        batch_op.drop_column('space_fee')

    # ### end Alembic commands ###
