"""empty message

Revision ID: c266f9857a18
Revises: 43e49ad04643
Create Date: 2025-03-27 12:01:05.095667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c266f9857a18'
down_revision = '43e49ad04643'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kingdom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lodging',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reg_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'registrations', ['reg_id'], ['id'])

    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_constraint('registrations_payment_id_fkey', type_='foreignkey')
        batch_op.drop_column('payment_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('registrations_payment_id_fkey', 'payment', ['payment_id'], ['id'])

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('reg_id')

    op.drop_table('lodging')
    op.drop_table('kingdom')
    # ### end Alembic commands ###
