"""empty message

Revision ID: c4c7f3125f86
Revises: 4751d9c93cdd
Create Date: 2025-03-24 13:30:40.856432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4c7f3125f86'
down_revision = '4751d9c93cdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_id', ['id'])
        
    with op.batch_alter_table('incidentreport', schema=None) as batch_op:
        batch_op.drop_constraint('incidentreport_regid_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'registrations', ['regid'], ['id'])

    with op.batch_alter_table('marshal_inspection', schema=None) as batch_op:
        batch_op.drop_constraint('marshal_inspection_regid_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'registrations', ['regid'], ['id'])

    with op.batch_alter_table('reg_bows', schema=None) as batch_op:
        batch_op.drop_constraint('reg_bows_regid_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'registrations', ['regid'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('reg_crossbows', schema=None) as batch_op:
        batch_op.drop_constraint('reg_crossbows_regid_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'registrations', ['regid'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('reglogs', schema=None) as batch_op:
        batch_op.drop_constraint('reglogs_regid_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'registrations', ['regid'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reglogs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('reglogs_regid_fkey', 'registrations', ['regid'], ['regid'])

    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_constraint('uq_id', ['id'])

    with op.batch_alter_table('reg_crossbows', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('reg_crossbows_regid_fkey', 'registrations', ['regid'], ['regid'], ondelete='CASCADE')

    with op.batch_alter_table('reg_bows', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('reg_bows_regid_fkey', 'registrations', ['regid'], ['regid'], ondelete='CASCADE')

    with op.batch_alter_table('marshal_inspection', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('marshal_inspection_regid_fkey', 'registrations', ['regid'], ['regid'])

    with op.batch_alter_table('incidentreport', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('incidentreport_regid_fkey', 'registrations', ['regid'], ['regid'])

    # ### end Alembic commands ###
