"""empty message

Revision ID: c66363197d7f
Revises: 6a19edaae4e4
Create Date: 2025-06-25 18:46:01.175686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c66363197d7f'
down_revision = '6a19edaae4e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merchant', schema=None) as batch_op:
        batch_op.alter_column('space_fee',
               existing_type=sa.INTEGER(),
               type_=sa.Double(),
               existing_nullable=False)
        batch_op.alter_column('merchant_fee',
               existing_type=sa.INTEGER(),
               type_=sa.Double(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merchant', schema=None) as batch_op:
        batch_op.alter_column('merchant_fee',
               existing_type=sa.Double(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('space_fee',
               existing_type=sa.Double(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
