"""empty message

Revision ID: c86ff2e4b280
Revises: c266f9857a18
Create Date: 2025-03-27 14:52:06.372658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c86ff2e4b280'
down_revision = 'c266f9857a18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_column('balance')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
