"""empty message

Revision ID: ccf2c8d4d4b5
Revises: abae80edd295
Create Date: 2025-05-27 19:26:51.748822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccf2c8d4d4b5'
down_revision = 'abae80edd295'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kingdom_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lodging_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'lodging', ['lodging_id'], ['id'])
        batch_op.create_foreign_key(None, 'kingdom', ['kingdom_id'], ['id'])
        batch_op.drop_column('lodging')
        batch_op.drop_column('kingdom')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kingdom', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lodging', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('lodging_id')
        batch_op.drop_column('kingdom_id')

    # ### end Alembic commands ###
