"""empty message

Revision ID: cdc16597c1e5
Revises: bd84cf86e7ad
Create Date: 2025-06-26 08:19:26.077961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdc16597c1e5'
down_revision = 'bd84cf86e7ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mbr_num_exp', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_column('mbr_num_exp')

    # ### end Alembic commands ###
