"""empty message

Revision ID: d2d7be5d723f
Revises: 5c45a8a497be
Create Date: 2025-03-25 13:08:50.710971

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd2d7be5d723f'
down_revision = '5c45a8a497be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_email', sa.String(), nullable=False))
        batch_op.alter_column('invoice_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('invoice_status',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.alter_column('invoice_status',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('invoice_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_column('invoice_email')

    # ### end Alembic commands ###
