"""empty message

Revision ID: df4f2462d433
Revises: 8b55ae9358a7
Create Date: 2025-02-17 10:17:47.912649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df4f2462d433'
down_revision = '8b55ae9358a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidentreport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regid', sa.Integer(), nullable=True),
    sa.Column('report_date', sa.DateTime(), nullable=True),
    sa.Column('reporting_user_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['regid'], ['registrations.regid'], ),
    sa.ForeignKeyConstraint(['reporting_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incidentreport')
    # ### end Alembic commands ###
