"""empty message

Revision ID: dfc8f3462f82
Revises: 41abf217dfb3
Create Date: 2025-03-24 12:52:39.263263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfc8f3462f82'
down_revision = '41abf217dfb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricesheet',
    sa.Column('arrival_date', sa.Date(), nullable=False),
    sa.Column('base_price', sa.Integer(), nullable=True),
    sa.Column('nmr', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('arrival_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pricesheet')
    # ### end Alembic commands ###
