"""empty message

Revision ID: e11e2859d9fb
Revises: 752addc103cf
Create Date: 2025-10-02 12:33:37.861172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e11e2859d9fb'
down_revision = '752addc103cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PayPal')
    with op.batch_alter_table('eventvariables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bas', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('cli', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('sec', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('web', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventvariables', schema=None) as batch_op:
        batch_op.drop_column('web')
        batch_op.drop_column('sec')
        batch_op.drop_column('cli')
        batch_op.drop_column('bas')

    op.create_table('PayPal',
    sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('key', name='PayPal_pkey')
    )
    # ### end Alembic commands ###
