"""empty message

Revision ID: e11e2859d9fb
Revises: 752addc103cf
Create Date: 2025-10-02 12:33:37.861172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e11e2859d9fb'
down_revision = '752addc103cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###
