"""empty message

Revision ID: f1473de2768e
Revises: acc2c2b889b1
Create Date: 2025-06-26 15:31:44.196373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1473de2768e'
down_revision = 'acc2c2b889b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.alter_column('space_fee',
               existing_type=sa.INTEGER(),
               type_=sa.Double(),
               existing_nullable=True)
        batch_op.alter_column('invoice_total',
               existing_type=sa.INTEGER(),
               type_=sa.Double(),
               existing_nullable=True)
        batch_op.alter_column('balance',
               existing_type=sa.INTEGER(),
               type_=sa.Double(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.alter_column('balance',
               existing_type=sa.Double(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('invoice_total',
               existing_type=sa.Double(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('space_fee',
               existing_type=sa.Double(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
