"""empty message

Revision ID: f14f0cdce8c8
Revises: e11e2859d9fb
Create Date: 2025-10-15 08:36:30.021184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f14f0cdce8c8'
down_revision = 'e11e2859d9fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventvariables', schema=None) as batch_op:
        batch_op.drop_column('web')
        batch_op.drop_column('sec')
        batch_op.drop_column('bas')
        batch_op.drop_column('cli')

    with op.batch_alter_table('merchant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personal_space', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merchant', schema=None) as batch_op:
        batch_op.drop_column('personal_space')

    with op.batch_alter_table('eventvariables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cli', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('bas', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sec', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('web', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
