"""empty message

Revision ID: f39d9a30dd60
Revises: 80b3c8a0f28b
Create Date: 2025-02-17 08:18:51.240144

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f39d9a30dd60'
down_revision = '80b3c8a0f28b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('martial_inspection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['regid'], ['registrations.regid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_constraint('registrations_chivalric_inspection_martial_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('registrations_rapier_inspection_martial_id_fkey', type_='foreignkey')
        batch_op.drop_column('chivalric_inspection')
        batch_op.drop_column('rapier_inspection_martial_id')
        batch_op.drop_column('chivalric_inspection_martial_id')
        batch_op.drop_column('chivalric_inspection_date')
        batch_op.drop_column('rapier_inspection')
        batch_op.drop_column('rapier_inspection_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rapier_inspection_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rapier_inspection', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('chivalric_inspection_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('chivalric_inspection_martial_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rapier_inspection_martial_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('chivalric_inspection', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('registrations_rapier_inspection_martial_id_fkey', 'users', ['rapier_inspection_martial_id'], ['id'])
        batch_op.create_foreign_key('registrations_chivalric_inspection_martial_id_fkey', 'users', ['chivalric_inspection_martial_id'], ['id'])

    op.drop_table('martial_inspection')
    # ### end Alembic commands ###
