"""empty message

Revision ID: f8d32542225a
Revises: 3288a3453aac
Create Date: 2025-03-25 11:42:17.320248

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f8d32542225a'
down_revision = '3288a3453aac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_number', sa.Integer(), nullable=True))
        batch_op.drop_constraint('payment_invoice_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'invoice', ['invoice_number'], ['invoice_number'])
        batch_op.drop_column('invoice_id')

    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_constraint('registrations_invoice_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'invoice', ['invoice_number'], ['invoice_number'])
        batch_op.drop_column('invoice_date')
        batch_op.drop_column('invoice_id')
        batch_op.drop_column('invoice_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_status', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('invoice_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('invoice_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('registrations_invoice_id_fkey', 'invoice', ['invoice_id'], ['invoice_number'])

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('payment_invoice_id_fkey', 'invoice', ['invoice_id'], ['invoice_number'])
        batch_op.drop_column('invoice_number')

    # ### end Alembic commands ###
