"""empty message

Revision ID: fab2684d185c
Revises: 26f228b9ba73
Create Date: 2025-06-27 12:40:41.597257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fab2684d185c'
down_revision = '26f228b9ba73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merchant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('application_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('checkin_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merchant', schema=None) as batch_op:
        batch_op.drop_column('checkin_date')
        batch_op.drop_column('application_date')

    # ### end Alembic commands ###
