"""empty message

Revision ID: fc37b216f849
Revises: 0ab82a252d98
Create Date: 2026-03-08 19:53:18.925275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc37b216f849'
down_revision = '0ab82a252d98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checkedin_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['checkedin_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('checkedin_by_id')

    # ### end Alembic commands ###
