"""empty message

Revision ID: fd4eb0146799
Revises: 947764bd5bd1
Create Date: 2025-08-02 15:28:03.856421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd4eb0146799'
down_revision = '947764bd5bd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduledevent_tags', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'scheduledevent', ['scheduledevent_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'tag', ['tag_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_scheduledevents', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'scheduledevent', ['scheduledevent_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('user_scheduledevents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('scheduledevent_tags', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
